version: "3"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./_sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: es
